# Generated by Django 3.1.6 on 2021-03-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('contract', models.CharField(max_length=60)),
                ('client', models.CharField(max_length=60)),
                ('tara', models.CharField(choices=[('Значение 1', 'Значение 1'), ('Значение 2', 'Значение 2')], max_length=300)),
                ('value', models.CharField(max_length=20)),
                ('comment', models.TextField()),
            ],
        ),
    ]
