# Generated by Django 3.1.6 on 2021-03-01 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contract',
        ),
    ]
