# Generated by Django 3.1.6 on 2021-03-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_order_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort', models.CharField(max_length=120)),
                ('width', models.CharField(max_length=120)),
                ('length', models.CharField(max_length=120)),
                ('height', models.CharField(max_length=120)),
                ('price', models.CharField(max_length=120)),
            ],
        ),
    ]
