# Generated by Django 3.1.6 on 2021-03-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='doc',
            field=models.CharField(default=123, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='gryz',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stamp',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='thickness',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
